name: Python application CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint code with flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Format code with black
      run: black . --line-length = 119
    - name: Sort imports PEP8 guidelines with isort
      run: isort . 
    - name: Test with pytest
      run: pytest
