name: Python CI

on: [push, pull_request]

jobs:
  build:

    name: Python default CI workflow
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort pytest
        pip install -r requirements.txt
    - name: Sort imports PEP8 guidelines with isort # Already done in pre-commit hooks
      run: isort . --check-only --diff
    - name: Test with pytest
      run: pytest
